server:
  port: 10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true # remenber to set it false in prod environment

eureka:
  instance:
    hostname: gateway
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    preferIpAddress: true # default false, but strong recommend to set true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ #,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/,http://discovery3:8763/eureka/
  
zuul:
  sensitiveHeaders: "*" # session can be transfered from gateway to applications 
  ignoredServices: '*' # all services are ignored except those defined below.
  routes:
    manage:
      path: /manage/**
      serviceId: demo-manage
      # stripPrefix: false  # default true   /hello/login  ->  /login , if false /hello/login  ->  /hello/login
    client-api: 
      path: /client-api/**
      serviceId: demo-client-api
      # stripPrefix: false  # default true   /hello/login  ->  /login , if false /hello/login  ->  /hello/login
#    remote-hello:
#      path: /remote-hello/**
#      url: http://localhost:9001 # url mode
