server:
  port: 10000

sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    
zuul:
  ignoredServices: '*' # all services are ignored except those defined below.
  routes:
    hello:
      path: /hello/**
      serviceId: demo
      stripPrefix: false  # default true   /hello/login  ->  /login , if false /hello/login  ->  /hello/login
    remote-hello:
      path: /remote-hello/**
      url: http://localhost:9001
      