server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: config
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}-${random.value}
    preferIpAddress: true # default false, but strong recommend to set true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ #,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/,http://discovery3:8763/eureka/
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lizhaosheng/springcloud-demo.git
          searchPaths: config-repo