server: 
  port: 0

eureka:
  instance: 
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}-${random.value}}
    hostname: ribbon-client
    preferIpAddress: true # default false, but strong recommend to set true
    metadataMap:
      turbine-cluster: MAIN # 集群名，给turbine使用，表明当前hystrix信息是属于哪个集群的
      env: dev
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # ,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/,http://discovery3:8763/eureka/
        
#say-hello:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:8090
#    ServerListRefreshInterval: 15000