server:
  port: ${PORT:0}

eureka:
  instance:
    hostname: demo-app
    preferIpAddress: true # default false, but strong recommend to set true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/ # ,http://discovery1:8761/eureka/,http://discovery2:8762/eureka/,http://discovery3:8763/eureka/
  